name: My First Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Hello World!"
     
     - name: Checkout
       uses: actions/checkout@v6.0.1

     - name: List files in the repository
       run: |
         echo "The repository ${{github.repository}} contains the following files:"
         tree
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo job: ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo job: ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo job: ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - run: "echo job: ${{github.job}}"

  job_5:
    strategy: 
      fail-fast: false
      max-parallel: 3
      matrix: 
        os_version: [macos-latest, ubuntu-latest]
        node_version: [12, 14, 16]
    name: my job 5
    runs-on: ${{ matrix.os_version}}
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version}}
